from typing import Any

class Context:
    def __init__(self, timeout: float | None = ..., max_heap_size: int | None = ...) -> None: ...
    @property
    def timeout(self) -> float:...
    @property
    def current_dir(self) -> str:...
    def set_current_dir(self, path: str) -> None:...
    def advance(self, wait_for_inspector: bool | None = ..., pump_v8_message_loop: bool | None = ...) -> bool:...
    def eval(self, code:str) -> Any:...
    def call(self, name:str, *args) -> Any:...
    def get_value(self, name:str) -> Any:...
    